development: &default
  adapter: postgresql
  encoding: unicode
  database: really_good_dev
  pool: 5
  username: postgres
  password:
  host: 127.0.0.1

test:
  <<: *default
  database: myapp_test

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>